import type { PlatformMeta } from './platforms';

export const COSE_PLATFORMS: PlatformMeta[] = [
    { type: 'infoq', name: 'InfoQ', icon: 'https://www.infoq.cn/favicon.ico', homepage: 'https://www.infoq.cn' },
    { type: 'tencentcloud', name: '腾讯云开发者社区', icon: 'https://cloud.tencent.com/favicon.ico', homepage: 'https://cloud.tencent.com/developer', disabled: true },
    { type: 'medium', name: 'Medium', icon: 'https://medium.com/favicon.ico', homepage: 'https://medium.com' },
    { type: 'aliyun', name: '阿里云开发者社区', icon: 'https://developer.aliyun.com/favicon.ico', homepage: 'https://developer.aliyun.com' },
    { type: 'volcengine', name: '火山引擎开发者社区', icon: 'https://www.volcengine.com/favicon.ico', homepage: 'https://www.volcengine.com' },
    { type: 'csdn', name: 'CSDN', icon: 'https://g.csdnimg.cn/static/logo/favicon32.ico', homepage: 'https://editor.csdn.net/md/', disabled: true },
    { type: 'juejin', name: '掘金', icon: 'https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web/static/favicons/favicon-32x32.png', homepage: 'https://juejin.cn', disabled: true },
    { type: 'wechat', name: '微信公众号', icon: 'https://mp.weixin.qq.com/favicon.ico', homepage: 'https://mp.weixin.qq.com/', disabled: true },
    { type: 'zhihu', name: '知乎', icon: 'https://static.zhihu.com/static/favicon.ico', homepage: 'https://www.zhihu.com', disabled: true },
    { type: 'toutiao', name: '今日头条', icon: 'https://mp.toutiao.com/favicon.ico', homepage: 'https://mp.toutiao.com', disabled: true },
    { type: 'segmentfault', name: '思否', icon: 'https://static.segmentfault.com/v-5e501fa4/favicon.ico', homepage: 'https://segmentfault.com', disabled: true },
    { type: 'cnblogs', name: '博客园', icon: 'https://www.cnblogs.com/favicon.ico', homepage: 'https://www.cnblogs.com', disabled: true },
    { type: 'oschina', name: '开源中国', icon: 'https://www.oschina.net/favicon.ico', homepage: 'https://my.oschina.net', disabled: true },
    { type: 'cto51', name: '51CTO', icon: 'https://www.51cto.com/favicon.ico', homepage: 'https://blog.51cto.com', disabled: true },
    { type: 'jianshu', name: '简书', icon: 'https://www.jianshu.com/favicon.ico', homepage: 'https://www.jianshu.com', disabled: true },
    { type: 'baijiahao', name: '百家号', icon: 'https://baijiahao.baidu.com/favicon.ico', homepage: 'https://baijiahao.baidu.com/', disabled: true },
    { type: 'wangyihao', name: '网易号', icon: 'https://mp.163.com/favicon.ico', homepage: 'https://mp.163.com', disabled: true },
    { type: 'sspai', name: '少数派', icon: 'https://cdn.sspai.com/favicon.ico', homepage: 'https://sspai.com', disabled: true },
    { type: 'sohu', name: '搜狐号', icon: 'https://mp.sohu.com/favicon.ico', homepage: 'https://mp.sohu.com', disabled: true },
    { type: 'bilibili', name: 'B站专栏', icon: 'https://www.bilibili.com/favicon.ico', homepage: 'https://member.bilibili.com/platform/upload/text', disabled: true },
    { type: 'weibo', name: '微博头条', icon: 'https://weibo.com/favicon.ico', homepage: 'https://card.weibo.com/article/v5/editor', disabled: true },
    { type: 'huaweicloud', name: '华为云开发者博客', icon: 'https://www.huaweicloud.com/favicon.ico', homepage: 'https://www.huaweicloud.com/developer', disabled: true },
    { type: 'huaweidev', name: '华为开发者文章', icon: 'https://developer.huawei.com/favicon.ico', homepage: 'https://developer.huawei.com', disabled: true },
    { type: 'twitter', name: 'Twitter Articles', icon: 'https://abs.twimg.com/favicons/twitter.ico', homepage: 'https://x.com', disabled: true },
    { type: 'qianfan', name: '百度云千帆', icon: 'https://qianfan.cloud.baidu.com/favicon.ico', homepage: 'https://qianfan.cloud.baidu.com', disabled: true },
    { type: 'alipayopen', name: '支付宝开放平台', icon: 'https://open.alipay.com/favicon.ico', homepage: 'https://open.alipay.com', disabled: true },
    { type: 'modelscope', name: 'ModelScope 魔搭社区', icon: 'https://modelscope.cn/favicon.ico', homepage: 'https://modelscope.cn', disabled: true },
    { type: 'douyin', name: '抖音文章', icon: 'https://www.douyin.com/favicon.ico', homepage: 'https://www.douyin.com', disabled: true },
    { type: 'xiaohongshu', name: '小红书', icon: 'https://www.xiaohongshu.com/favicon.ico', homepage: 'https://www.xiaohongshu.com', disabled: true },
    { type: 'elecfans', name: '电子发烧友', icon: 'https://www.elecfans.com/favicon.ico', homepage: 'https://www.elecfans.com', disabled: true },
    { type: 'douban', name: '豆瓣', icon: 'https://www.douban.com/favicon.ico', homepage: 'https://www.douban.com/note/create', disabled: true },
];
